version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: simstech
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: simstech
    ports:
      - "5432:5432"
    networks:
      - backend

app:
    image: SimsTech
    environment:
      SPRING_DATASOURCE_URL: postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    depends_on:
      - db

networks:
  backend:
    driver: bridge