version: '3'
services:
  postgres:
    image: postgres:16
    container_name: postgres_container
    environment:
      POSTGRES_USER: simstech
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: simstech
    ports:
      - "5432:5432"
    networks:
      - backend

networks:
  backend:
    driver: bridge